Move to Stack for build system and support 7.10

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,35 +1,57 @@
 sudo: false
-language: haskell
+language: c
+
+cache:
+  directories:
+    - $HOME/.gcc-arm-embedded
+    - $HOME/.stack
+
 addons:
   apt:
-    sources:
-      - hvr-ghc
     packages:
-      - cabal-install-1.22
-      - alex-3.1.4
-      - happy-1.19.5
-      - lib32ncurses5
+      - gcc-multilib
+
+matrix:
+  include:
+    - env: GHCVER=7.8.4 STACK_YAML=stack.yaml
+      addons: {apt: {packages: [ghc-7.8.4,gcc-multilib], sources: [hvr-ghc]}}
+    - env: GHCVER=7.10.3 STACK_YAML=stack-7.10.yaml
+      addons: {apt: {packages: [ghc-7.10.3,gcc-multilib], sources: [hvr-ghc]}}
+    - env: GHCVER=8.0.1 STACK_YAML=stack-8.0.yaml
+      addons: {apt: {packages: [ghc-8.0.1,gcc-multilib], sources: [hvr-ghc]}}
+
+  allow_failures:
+    - env: GHCVER=8.0.1 STACK_YAML=stack-8.0.yaml
+
 before_install:
-- mkdir -p gcc-arm-embedded
-- wget https://launchpad.net/gcc-arm-embedded/4.9/4.9-2015-q2-update/+download/gcc-arm-none-eabi-4_9-2015q2-20150609-linux.tar.bz2 -O- | tar xjf - -C gcc-arm-embedded
-- export PATH="$(echo $PWD/gcc-arm-embedded/*/bin):/opt/cabal/1.22/bin:/opt/alex/3.1.4/bin:/opt/happy/1.19.5/bin:$PATH"
-- arm-none-eabi-gcc --version
+  # Download and unpack the stack executable
+  - mkdir -p ~/.local/bin
+  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
+  # Set up the ARM GCC toolchain
+  - if [ ! -d $HOME/.gcc-arm-embedded/*/bin ];
+    then
+      mkdir -p $HOME/.gcc-arm-embedded;
+      wget https://launchpad.net/gcc-arm-embedded/4.9/4.9-2015-q2-update/+download/gcc-arm-none-eabi-4_9-2015q2-20150609-linux.tar.bz2 -O- | tar xjf - -C $HOME/.gcc-arm-embedded;
+    fi
+  - echo $HOME/.gcc-arm-embedded/*/bin
+  - ls $HOME/.gcc-arm-embedded/*/bin
+  - export PATH=$HOME/.local/bin:/opt/ghc/$GHCVER/bin:$PATH
+  - ghc --version
+  - export PATH="$(echo $HOME/.gcc-arm-embedded/*/bin):$PATH"
+  - arm-none-eabi-gcc --version
+
 install:
-- git clone https://github.com/galoisinc/ivory
-- export IVORY_REPO=$PWD/ivory
-- git clone https://github.com/galoisinc/tower
-- export TOWER_REPO=$PWD/tower
+  # Check out depenendency repos, then check out the branch that
+  # matches the current branch name in this repo. If one doesn't
+  # exist, don't fail, in case we're branched in this repo but just
+  # depending on master elsewhere.
+  #
+  # Travis seems to have no problem with the multi-line if above,
+  # but barfs when we format this one nicely.
+  - for repo in ivory tower; do git clone https://github.com/galoisinc/$repo; (cd $repo; git checkout $TRAVIS_BRANCH) || true; export $(echo ${repo^^} | tr - _)_REPO=$PWD/$repo; done
+  # tweak the relative paths in stack.yaml
+  - export STACK_YAML=$PWD/$STACK_YAML
+  - sed -i "s;\.\./;$PWD/;g" $STACK_YAML
+
 script:
-- make $ENV_TEST_TARGET
-ghc:
-- 7.8
-env:
-- ENV_TEST_TARGET=ivory-freertos-bindings
-- ENV_TEST_TARGET=ivory-bsp-stm32
-- ENV_TEST_TARGET=tower-freertos-stm32
-- ENV_TEST_TARGET=tower-freertos-stm32-tests
-- ENV_TEST_TARGET=ivory-bsp-tests
-notifications:
-  slack:
-    secure: HV4BpAHw/LibvN0LRLJIZkhAtFWr77FnG9z2+u4TWXIwdkcTzFw+zB7S3AvzY0PpF9Y77/9/tQlipm+frV2fYk+2+zNYZnBYiPvgfu10JJql8B1jifiymBFXPOqYahJk9irApf0CAzdDj6eFUH/YX480eV4Xpnw+WcPiig5WBpg=
-    secure: A2JXPOP11K/4praaswuJ17zcXLo1SsF/WBZ5sO+c18scjAKCLeQuci1xUDUCZXspeDGfnJq0hlz95qbISu7LtoK55zQPt0l/4P0es7x34paSrEs5Ca8lXK5qim2ozfvb6TIeuYLnS/Asj3fFQmuUlbWwkxlt3pcJFi0wxaJjt8o=
+- make travis-test
